version: "3"

services: 
         
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
      container_name: elasticsearch_springboot
      environment:
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - "discovery.type=single-node"
          - xpack.security.enabled=false
      ports:
          - "9200:9200"
      volumes:
          - elasticsearch_data:/usr/share/elasticsearch/data
      networks:
         - elk-network

    logstash:
      image: docker.elastic.co/logstash/logstash:8.3.3
      container_name: logstash_springboot
      volumes:
        - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
        - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      ports:
        - "5044:5044"
        - "5000:5000/tcp"
        - "5000:5000/udp"
        - "9600:9600"
      environment:
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
        - elk-network
      depends_on:
        - elasticsearch      

networks:
  elk-network:
    driver: bridge

volumes:
    elasticsearch_data:
        driver: local
        

